# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 558b6388adc76334136a1cf8667b2e5472231da6aff338911e50f6a3fd5c1042a7b913c010a2ae40aac6dc24f83e3d84d0205a17832300020b15c785eeea157f

test:
  secret_key_base: 6bd897374edcc7d3c4e2b44da1b044359f97faf8d2bdbf04e32dfdc315a67832de2fcb02b2fac1705678d8fb11a368a75a5b6fcb4027d54a84896df809d4184e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
